### ISSUE TITLE
[Nhóm#9] Lỗi giao diện - button đè lên nhau ở giao diện cho điện thoại - https://nhattao.com/

### ISSUE THREAD

**Issue by khiemhg1202** [UEHMonQAQC/ST_K45_01#108]
A. Web browser: Google Chrome
B. Các bước phát hiện lỗi:
i. #1 truy cập vào trang https://nhattao.com/
ii. #2 chọn hiển thị giao diện ở chế độ điện thoại iphone 6/7/8
C. Kết quả thực tế: button đè lên nhau
![UI](https://user-images.githubusercontent.com/91679167/140780513-c6ebb1eb-46d1-4190-b4f0-4c3566b46206.png)
D. Kết quả mong đợi: các button không đè lên nhau

**Comment by 31141021447** [comment]
Đấy là icon của web, không phải 2 button chồng nhau

**Comment by khiemhg1202** [comment]
Nhưng mà nó vẫn đè lên nhau mà anh

**Comment by 31141021447** [comment]
![image](https://user-images.githubusercontent.com/92357000/141070861-6175b402-785b-464f-9223-4da9497a69ee.png)

**Comment by 31141021447** [comment]
Đấy là biểu tượng của trang web, không phải button

**Comment by 31141021447** [comment]
![IMG_3420](https://user-images.githubusercontent.com/92357000/141071312-977686a0-69ce-4d9f-925e-e9a81b00acfb.JPG)
