### ISSUE TITLE
[Nhóm#8] Lỗi chức năng - Hiển thị họ tên và MSSV không đúng - https://shcd.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191024554** [UEHMonQAQC/ST_K45_01#120]
a. Web browser: Google Chrome - Version 95.0.4638.69 (Official Build) (64-bit).

b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang [https://shcd.ueh.edu.vn/](https://shcd.ueh.edu.vn/)
ii. #2: Tiến hành đăng nhập (Sử dụng mail sinh viên UEH để đăng nhập).

c. Kết quả thực tế: Họ tên và MSSV hiển thị không đúng vị trí.
![image](https://user-images.githubusercontent.com/24526239/141164162-1a093cd0-2323-4d85-9e5e-a6c9dd66f309.png)

d. Kết quả mong đợi: Họ tên và MSSV được hiển thị đúng vị trí.
![image](https://user-images.githubusercontent.com/24526239/141164059-82b76b04-65cd-4538-9e01-94070f251df0.png)

**Comment by 31191024554** [comment]
@31191024773 mình nghĩ cái này là lỗi chức năng mà, 
![image](https://user-images.githubusercontent.com/24526239/141802290-571c46c8-e030-4bdc-bd9e-b679d4f9e9bb.png)
Chức năng này của server họ import dữ liệu lên, xử lý sai. Hiển thị sai là đúng mà.
Sinh viên không được phép sửa Họ & Tên.

**Comment by 31191024773** [comment]
@31191024554 cái này do trường mình quy định như vậy á bạn nên nó không phải là lỗi
