### ISSUE TITLE
[Nhóm#2] Lỗi chức năng- Lỗi checkbox khộng hoạt động- https://student.ueh.edu.vn

### ISSUE THREAD

**Issue by anhle1403** [UEHMonQAQC/ST_K45_01#124]
Web Browser: Google Chrome
**Các bước để phát hiện lỗi:**
#1: Đăng nhập vào trang web bằng tài khoản người học : [https://student.ueh.edu.vn](url)
#2: Vào trang thông tin cá nhân

**Kết quả thực tế**
![image](https://user-images.githubusercontent.com/92585805/141309434-5fb4576a-f400-433c-aa3a-b6a79fcebee5.png)

**Kết quả mong đợi**
 - Hiển thị dấu tích lên checkbox

**Comment by 31191020041** [comment]
Trên trang không cập nhật ngày vào đoàn nên không có dấu tích trên checkbox

**Comment by anhle1403** [comment]
Dạ em đã hiểu rồi, em cảm ơn thầy ạ!

Vào Th 2, 15 thg 11, 2021 vào lúc 21:20 Nguyễn Thái Hiền <
***@***.***> đã viết:
