### ISSUE TITLE
[Nhóm #3] Lỗi chức năng - Lỗi chức năng bình luận không hoạt động - https://bienniensukienhsv.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191025986** [UEHMonQAQC/ST_K45_01#132]
A. Web browser: Microsoft Egde
B. Các bước phát hiện lỗi :
i. #1 Truy cập vào trang [bienniensukienhsv.ueh.edu.vn](https://bienniensukienhsv.ueh.edu.vn)
ii. #2 Truy cập vào bài viết bất và kéo xuống mục bình luận với điều kiện trình duyệt đã được lưu mật khẩu Facebook.
![image](https://user-images.githubusercontent.com/92624705/141498071-01f0308a-4cf4-46f5-aa65-b7d820c23404.png)
C. Kết quả thực tế: chức năng bình luận không hoạt động.
D. Kết quả mong đợi: chức năng bình luận hoạt động bình thường.
![image](https://user-images.githubusercontent.com/92624705/141498418-691fcb60-b2d2-4f46-a5d6-946a6cbd8c3b.png)

**Comment by 31191020041** [comment]
mình đã kiểm tra và bình luận được, nên đây không phải lỗi nhé
