### ISSUE TITLE
[Nhóm#9] Lỗi chức năng - Button chia sẻ bằng Google bị lỗi - https://nhattao.com/

### ISSUE THREAD

**Issue by duchung0908** [UEHMonQAQC/ST_K45_01#133]
A. Web browser: Google Chrome
B. Các bước phát hiện lỗi:
i. #1 Truy cập vào trang https://nhattao.com/ và đăng nhập bằng tài khoản bất kì 
(TK: tranphuongminh18@gmail.com
MK: 90436)
ii. #2 Chọn " Hồ sơ của bạn"
![image](https://user-images.githubusercontent.com/90156544/141614315-418f6f11-84b4-4714-b139-b87a7b273ccd.png)
iii. #3 Chọn chia sẻ trang này bằng Google+
C. Kết quả thực tế: Liên kết bị lỗi 
![image](https://user-images.githubusercontent.com/90156544/141614370-0cc42a8e-7dab-4654-bdc1-48328c17335b.png)
D. Kết quả mong đợi: Chuyển đến trang chia sẻ bằng Google

**Comment by 31141021447** [comment]
Google + đã bị khai tử vào năm 2019 nên trang web liên quan tới Google + sẽ không còn có thể truy cập được
