### ISSUE TITLE
[Nhóm#6] - Lỗi giao diện - Liên kết trang không hiển thị - https://vieclam.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191023095** [UEHMonQAQC/ST_K45_01#140]
Web Browser: Opera
Các bước phát hiện lỗi:

#1: Truy cập trang web:  https://vieclam.ueh.edu.vn
#2: Kéo xuống cuối trang web và chọn mục App store hoặc Google Play
![image](https://user-images.githubusercontent.com/91049432/141667183-b8b9663d-ddac-4a6a-a42b-c757f33a72ca.png)

Kết quả thực tế: Load lại trang chủ 
![image](https://user-images.githubusercontent.com/91049432/141667199-413c88af-36b0-4f3f-8a98-6149e2918cd5.png)

Kết quả mong muốn: Liên kết tới một trang để tải ứng dụng trên App store hoặc Google play

**Comment by 31191026273** [comment]
App store và Google play chỉ áp dụng cho điện thoại, đây là không sử dụng máy chủ tương thích, không phải lỗi

**Comment by 31141021447** [comment]
Nhóm sử dụng thiết bị di động để xác nhận kỹ xem lỗi có thực hiện được không
