### ISSUE TITLE
[Nhóm#6] - Lỗi giao diện - Một nữa nút nhấn quay về đầu trang không thể nhấn được - https://vieclam.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191023095** [UEHMonQAQC/ST_K45_01#141]
Web Browser: Opera
Các bước phát hiện lỗi:

#1: Truy cập vào trang web: https://vieclam.ueh.edu.vn
#2: Kéo xuống cuối trang web và nhấn vào nữa trên của nút quay về đầu trang

![image](https://user-images.githubusercontent.com/91049432/141667315-87954844-8ccd-42f6-a121-9dbcecb230cb.png)

Kết quả thực tế: Không thể nhấn nút quay về đầu trang

Kết quả mong muốn: Có thể nhấn nút quay về đầu trang

**Comment by 31191026273** [comment]
Lỗi trùng với k44
