### ISSUE TITLE
[Nhóm#4] – Lỗi chức năng –Cho phép tải file bất kì trong ảnh đại diện tải code lên - https://sharecode.vn/

### ISSUE THREAD

**Issue by 31191023261** [UEHMonQAQC/ST_K45_01#151]
a. Google Chrome version 95.0.4638.69.
b. Kết quả thực tế: Trong ảnh đại diện cho phép tải lên file bất kì
 
![image](https://user-images.githubusercontent.com/92630786/141681608-104e6794-0af5-4393-aa80-47d5863807d0.png)

c. Kết quả mong đợi: Thông báo chỉ được chọn file ảnh
 
![image](https://user-images.githubusercontent.com/92630786/141681612-76e8b1a1-448a-4c5b-8cc3-2def0bf62494.png)

d. Các bước phát hiện lỗi:
i. #1: Truy cập https://sharecode.vn/.
ii. #2: Chọn “Tải lên”
![image](https://user-images.githubusercontent.com/92630786/141681621-c5e9c8c0-bfde-41a2-b823-ce4ebe093442.png)
 
iii. #3: Vào mục tải ảnh lên và chọn file bất kì
iv. #a: Nhấn chọn “Chọn ảnh”

**Comment by 31191024773** [comment]
@31141021447 bị trùng lỗi #144
