### ISSUE TITLE
[Nhóm#8] Lỗi chức năng - Lỗi tìm kiếm với nội dung để trống - https://shcd.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191024554** [UEHMonQAQC/ST_K45_01#162]
a. Web browser: Google Chrome - Version 95.0.4638.69 (Official Build) (64-bit).

b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang [https://shcd.ueh.edu.vn/](https://shcd.ueh.edu.vn/)
ii. #2: Tiến hành đăng nhập.
iii. #3: Để trống nội dung ở phần box search "Tìm kiếm khóa học".
![image](https://user-images.githubusercontent.com/24526239/141718531-86049bbe-0d48-4aa0-b2a8-170fbbed509f.png)
iv. #4: Click chọn icon kính lúp bên cạnh box search.

c. Kết quả thực tế: Tìm kiếm thành công với keyword "Tìm kiếm khoá học"
![image](https://user-images.githubusercontent.com/24526239/141718611-cd2044a8-7fe9-4e14-8ef0-4d28b8aedcee.png)

d. Kết quả mong đợi: Tìm kiếm thành công với keyword trống hoặc hiển thị thông báo keyword không được để trống.

**Comment by 31191024773** [comment]
@31191024554 nó mặc định như vậy á bạn

**Comment by 31191024554** [comment]
> @31191024554 nó mặc định như vậy á bạn

Sao lại nói là mặc định như vậy được, bạn nói vậy mình chịu luôn á.
Cái chữ Tìm kiếm khóa học khi bạn đưa trỏ chuột vào nó là placeholder của input thôi, chứ nó đâu phải là value của input đâu.
![image](https://user-images.githubusercontent.com/24526239/141805653-a582643a-bfbe-402f-8903-441c512ceca4.png)
Mình chưa thấy trang nào lại có mặc định như vậy luôn.

**Comment by 31191024773** [comment]
@31191024554 mình check thì nó mặc định nếu value là khoảng trống thì gán value bằng tìm kiếm khóa học
![Screenshot (213)](https://user-images.githubusercontent.com/92364366/142418253-38cefa58-a97f-4549-ae89-fe14a84f0660.png)
