### ISSUE TITLE
[Nhóm#9] Lỗi chức năng - Checkbox không hoạt  động - https://nhattao.com/

### ISSUE THREAD

**Issue by duchung0908** [UEHMonQAQC/ST_K45_01#163]
A. Web browser: Google Chrome
B. Các bước phát hiện lỗi:
i. #1 Truy cập vào trang https://nhattao.com/ và đăng nhập bằng tài khoản bất kì
(TK: tranphuongminh18@gmail.com
MK: 90436)
ii. #2 Click vào "Hồ sơ của bạn" và chọn "Nâng cấp lên tài khoản thương gia"
![image](https://user-images.githubusercontent.com/90156544/141726264-66861bbe-1f62-4677-8293-fae1ab27b3fb.png)
iii. #3 Click "Bấm vào đây để sử dụng" bên dưới
![image](https://user-images.githubusercontent.com/90156544/141726368-a5054f57-49de-4cf2-a3f1-b45f058c1f75.png)
iv. #4 Chọn số tháng bất kì và thêm click checkbox "Xóa"
![image](https://user-images.githubusercontent.com/90156544/141726721-fe0cffd8-17b0-4698-90f9-cab64ab2fede.png)
C. Kết quả thực tế: Checkbox "Xóa" không hoạt động
D. Kết quả mong đợi: Checkbox "Xóa" hoạt động hoặc hiện thông báo nếu có thêm yêu cầu

**Comment by 31141021447** [comment]
Phải có chọn được mã khuyến mãi hợp lệ thì nút check box xóa mới hoạt động
