### ISSUE TITLE
[Nhóm#9] Lỗi chức năng - Không hiện thông báo và button không hoạt động khi chọn thiếu captcha - https://nhattao.com/

### ISSUE THREAD

**Issue by duchung0908** [UEHMonQAQC/ST_K45_01#165]
A. Web browser: Google Chrome
B. Các bước phát hiện lỗi:
i. #1 Truy cập vào trang https://smartlib.ueh.edu.vn/ và chọn Feedback bên phải
![image](https://user-images.githubusercontent.com/90156544/141729391-4e165f93-c1a4-49a0-8d32-708f4a44143c.png)
ii. #2 Nhập comment bất kì, không click check captcha và click button "Submit"
C. Kết quả thực tế: Button "Submit" không hoạt động và không hiện bất kì thông báo thiếu captcha
![image](https://user-images.githubusercontent.com/90156544/141729595-092d0cbe-6fa0-4033-9296-0b5315ebc114.png)
D. Kết quả mong đợi: Button "Submit" hoạt động và hiện thông báo bị thiếu captcha

**Comment by 31141021447** [comment]
Phải tích vào capcha rồi chọn đúng thì chức năng submit sẽ hoạt động bình thường
