### ISSUE TITLE
[Nhóm#2] Lỗi chức năng - Lỗi hiện thị sai thông tin  - https://student.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191026415** [UEHMonQAQC/ST_K45_01#174]
Web Browser: Google Chrome
**Các bước để phát hiện lỗi:**
#1: Đăng nhập vào trang web bằng tài khoản người học : https://student.ueh.edu.vn
#2: Chọn **Kết quả học tập**
#3: Kéo xuống phần **Năm học: 2020 - Học kỳ: HKC**
#4: Click vào xem chi tiết của 1 môn học bất kì 

Kết quả thực tế
Trọng số **Điểm Thi giữa học phần** là 1%.
![err3](https://user-images.githubusercontent.com/92578055/141800704-c68e6f6a-7929-4ee4-91cd-81a59006782f.png)

Kết quả mong đợi
Trọng số **Điểm Thi giữa học phần**  đúng giá trị

**Comment by 31191020041** [comment]
Trọng số điểm thi này là do người ta nhập tay vào
