### ISSUE TITLE
[Nhóm#8] Lỗi chức năng - Lỗi chức năng lọc khi để trống filter, trang "Danh sách thành viên" - https://shcd.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31191024554** [UEHMonQAQC/ST_K45_01#182]
a. Web browser: Google Chrome - Version 95.0.4638.69 (Official Build) (64-bit).

b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang [https://shcd.ueh.edu.vn/](https://shcd.ueh.edu.vn/)
ii. #2: Tiến hành đăng nhập.
iii. #3: Click chọn icon ">" bên cạnh khóa học ở bảng "Điều hướng".
![image](https://user-images.githubusercontent.com/24526239/141816876-ededf0e7-4dce-483c-98b0-a7e58b7ae30c.png)
iv. #4: Click chọn "Danh sách thành viên" để chuyển hướng đến trang danh sách thành viên.
v. #5: Ở phần filter, click vào input select "Chọn".
![image](https://user-images.githubusercontent.com/24526239/141817122-ff0f8b08-782a-4cd1-bb25-89a701d7f1d0.png)
vi. #6: Click chọn option "Không hoạt động từ hơn" trong input select.
![image](https://user-images.githubusercontent.com/24526239/141817261-3146d3a3-5087-4502-ac2c-9c4fd4961869.png)
vii. #7: Click icon "x" bên cạnh "Ngày 1" để xóa filter mặc định.
![image](https://user-images.githubusercontent.com/24526239/141817379-03e0f8b2-a6cb-4c6e-a4e9-7583638fbff3.png)
viii. #8: Click button "Áp dụng bộ lọc".

c. Kết quả thực tế: Xuất hiện exception NULL.
![image](https://user-images.githubusercontent.com/24526239/141817496-a2269d86-adbf-40d6-8c7a-e231b77cdc86.png)

d. Kết quả mong đợi: Lọc thành công với kết quả là danh sách thành viên không hoạt động từ hơn 0 ngày. Hoặc thông báo số ngày không được để trống.

**Comment by 31191024773** [comment]
@31191024554 nó hiển thị thông báo số ngày không được để trống rồi á bạn " The value supplied was of type 'NULL'. An integer was expected "
