### ISSUE TITLE
[Nhóm#2] Lỗi chức năng- Lỗi không đồng nhất - https://fullstack.edu.vn

### ISSUE THREAD

**Issue by anhle1403** [UEHMonQAQC/ST_K45_01#188]
Web Browser: Google Chrome
**Các bước để phát hiện lỗi:**
#1: Đăng nhập vào trang web ( Đăng nhập bằng gmail; facebook ...v...v ) https://fullstack.edu.vn
#2: chọn **Blog** để xem blog mình đã đăng

**Kết quả thực tế**
- Nhưng khi bấm vào bài đăng thì bên trong đã được duyệt
![12](https://user-images.githubusercontent.com/92585805/142617239-ee34122b-9c13-4db3-bf83-4a72ae91175c.png)
![13](https://user-images.githubusercontent.com/92585805/142617333-3b7166b4-f860-49a9-a96b-d163cfe985a1.png)

**Kết quả mong đợi**
-Dữ liệu được đồng nhất

**Comment by 31141021447** [comment]
Mình đã test và không gặp lỗi giống như bạn mô tả 
![image](https://user-images.githubusercontent.com/92357000/142858508-8f37bf52-3677-4e4c-bd36-5f666dce48da.png)
![image](https://user-images.githubusercontent.com/92357000/142858528-b1c370cc-ae07-4e51-a4c5-6e0270f1860e.png)

**Comment by anhle1403** [comment]
Dạ anh thử để vài ngày sau anh vào lại thử ạ, chứ mới đăng thì nó không bị
lỗi

Vào 7:02 CH, Th 2, 22 thg 11, 2021 Nguyễn Anh Tuấn ***@***.***>
đã viết:
