### ISSUE TITLE
[Nhóm#3] Lỗi phi chức năng - Lỗi đăng nhập- https://bienniensukienhsv.ueh.edu.vn

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/ST_K45_01#209]
A. Web browser: Microsoft Egde
B. Các bước phát hiện lỗi :
i. #1 Truy cập vào trang bienniensukienhsv.ueh.edu.vn
ii. #2 Truy cập vào một sự kiện bất kỳ
iii. #3 Tìm đến phần bình luận và đăng nhập bằng Facebook (Sign in with Facebook). Thực hiện bình luận nội dung bất kỳ (không ẩn danh), sau đó log-out
iiii. #4 Đăng nhập lại bằng Google (Sign in with Google) .Thực hiện bình luận nội dung bất kỳ (không ẩn danh), sau đó log-out.
iiiii. #5 Đăng nhập lại bằng Facebook.
C. Kết quả mong đợi: tài khoản facebook được đăng  nhập vào hệ thống.
D. Kết quả thực tế: tài khoản google được đăng nhập và hệ thống

**Comment by 31191020041** [comment]
Mình vẫn đăng nhập được bình thường. Đây không phải lỗi

**Comment by ghost** [comment]
https://drive.google.com/file/d/1V08UTEAlExiTYPJOvu_a1f8VjtqyMNuJ/view?usp=sharing
Mình gửi nhóm QA video lỗi này.

**Comment by 31191020041** [comment]
Bạn ơi, có thể là do bạn dùng email đó để tạo tài khoản fb nên nó hiện luôn tên email của bạn. Mình đã thử giống video bạn và có tài khoản fb mình dùng email tạo fb đăng nhập thì nó hiện lên hộp thoại hỏi tài khoản này đã đăng nhập bằng email và chỉ được đăng nhập bằng email đó. Mình thử lại với tài khoản fb mới hoàn toàn và không có vấn đề gì hết nhé

**Comment by 31191020041** [comment]
Gửi nhóm video mình làm thử
https://drive.google.com/file/d/1Tp9o5wJEmVJ9VM2wA86IKIaAwKN3v7YN/view?usp=sharing
