### ISSUE TITLE
[Nhóm #3] Lỗi giao diện - Lỗi footer hiển thị đè comment - https://bienniensukienhsv.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191025686** [UEHMonQAQC/ST_K45_01#211]
A. Web browser: Microsoft Egde
B. Các bước phát hiện lỗi:
i. #1 Truy cập vào trang https://bienniensukienhsv.ueh.edu.vn/Detail?Id=115&name=Ng%C3%A0y+h%E1%BB%99i+S%E1%BB%A9c+tr%E1%BA%BB+Kinh+t%E1%BA%BF+2013 ở kích thước màn hình 280x653 pixel (Galaxy Fold)
ii. #2 Kéo đến vị trí cuối cùng như bên dưới:
![image](https://user-images.githubusercontent.com/92577010/142731771-e346c5f8-b558-4cee-8e87-0037baefecd1.png)
C. Kết quả thực tế: Footer che mất các comment cũ hơn, không thể scroll để xem tất cả comment.
D. Kết quả mong đợi: Footer hiện thị bên dưới comment cuối cùng.

**Comment by 31191020041** [comment]
mình đã kiểm tra và không bị che mất bình luận. Đây không phải lỗi

**Comment by 31191025686** [comment]
https://user-images.githubusercontent.com/92577010/142874259-f7fa61d4-2e0b-4bd8-9301-706683c6366c.MP4

**Comment by 31191025686** [comment]
Bạn ơi xem lại giúp mình nha, mình vừa quay màn hình lại luôn đó

**Comment by 31191025686** [comment]
@31191020041

**Comment by 31141021447** [comment]
Bạn phải sử dụng điện thoại có kích thước màn hình đúng như mô tả để test lỗi này, chỉ dùng PC để test thì không thể khẳng định là lỗi xuất hiện do điện thoại được

**Comment by 31191025686** [comment]
Vậy bạn có thể chụp giúp mình ảnh bạn test footer không che comment không ạ?

**Comment by 31191020041** [comment]
![image](https://user-images.githubusercontent.com/92364035/142876653-291abc46-20fa-4b5d-afd1-90d244875879.png)
đây nhé bạn

**Comment by 31191025686** [comment]
Okay mình cám ơn bạn nhen
