### ISSUE TITLE
[Nhóm#2] Lỗi phi chức năng - Không hiện thị trực tiếp phòng ban  - https://student.ueh.edu.vn 

### ISSUE THREAD

**Issue by 31191026415** [UEHMonQAQC/ST_K45_01#214]
Web Browser: Google Chrome
Các bước để phát hiện lỗi:
#1: Đăng nhập vào trang web bằng tài khoản người học : https://student.ueh.edu.vn
#2 Chọn chức năng **Liên hệ - góp ý**
#3 Click vào **Phòng ban** ( Thì không có hiển thị ra danh sách phòng ban) 

![err5](https://user-images.githubusercontent.com/92578055/142751100-8dc45261-290e-4343-b340-e33f67ef32a1.png)

#4 Nhập **Tiêu đề** hoặc **Nội dung**  xong bấm **Gửi**

Kết quả thức tế: 
Danh sách phòng ban hiện ra, và có thể lựa chọn được các phòng ban

![err4](https://user-images.githubusercontent.com/92578055/142751025-e6b7a20d-5a99-47dc-a78d-51522b8dfad4.png)

Kết quả mong đợi: 
Khi chọn chức năng **Liên hệ - góp ý** thì click vào **Phòng ban** phải hiện thị ra danh sách phòng ban luôn

**Comment by 31191020041** [comment]
Lỗi này trùng với lỗi 62, lỗi chức năng của nhóm
