### ISSUE TITLE
[Nhóm#4] – Lỗi chức năng – Lỗi không thể truy cập link liên kết - https://sharecode.vn/

### ISSUE THREAD

**Issue by 31191023261** [UEHMonQAQC/ST_K45_01#222]
a. Google Chrome version 95.0.4638.69.
b. Kết quả thực tế: Trong ảnh đại diện cho phép tải lên file bất kì
![image](https://user-images.githubusercontent.com/92630786/142832115-b6ba8836-7756-4684-b020-7ac4773d3c16.png)
c. Kết quả mong đợi: Truy cập vào trang liên kết
d. Các bước phát hiện lỗi:
i. #1: Truy cập https://sharecode.vn/.
ii. #2: Tại trang chủ truy cập vào hình ảnh dưới phần "Thông Báo"
![2 1](https://user-images.githubusercontent.com/92630786/142832594-e3bb83cd-dca2-4b44-b4e6-f1886e873b14.png)

**Comment by 31141021447** [comment]
Banner quảng cáo của bên thứ 3 đã hết hiệu lực
![image](https://user-images.githubusercontent.com/92357000/142870460-58f5c471-3a37-4f0a-9dda-55120fe564ff.png)
