### ISSUE TITLE
[Nhóm#4] Lỗi giao diện - Ô tìm kiếm che khuất phần tử khác trong header treo - https://sharecode.vn/

### ISSUE THREAD

**Issue by 31191023111** [UEHMonQAQC/ST_K45_01#224]
a. Google Chrome version 95.0.4638.69.
b. Kết quả thực tế: Phần ô tìm kiếm của header treo khi không ở đầu trang lấn sang mục khác khi rà chuột lên.
![image](https://user-images.githubusercontent.com/92569399/142832551-72d49c5b-9e51-4064-9b9e-3bdf4bd55575.png)
c. Kết quả mong đợi: Phần ô tìm kiếm hiển thị hợp lý để không che khuất các phần tử khác trong header.
d. Các bước phát hiện lỗi:
i. #1: Truy cập https://sharecode.vn/.
ii. #2: Kéo trang xuống phía dưới để hiển thị header treo (Header hiển thị thay thế cho header phía trên đầu).
![image](https://user-images.githubusercontent.com/92569399/142833249-5d38c040-c2ec-4dda-97c6-0a778d56d5be.png)
iii. #3: Rà chuột lên icon kính lúp để hiển thị ô tìm kiếm.

**Comment by 31141021447** [comment]
Đây không phải là lỗi, trang tìm kiếm chỉ hiện ra khi trỏ chuột tới, không phải hiện ra liên tục
