### ISSUE TITLE
[Nhóm#7] Lỗi phi chức năng- Lỗi load trang-http://muaban.net/

### ISSUE THREAD

**Issue by 31191024561** [UEHMonQAQC/ST_K45_01#225]
a. web browser: Cốc cốc
b. Các bước phát hiện lỗi
i. Truy cập vào trang http://muaban.net/
ii. Vào trang thông tin cá nhân (Đăng nhập bằng tài khoản Facebook)
iii. Chọn danh mục Thông tin tài khoản
iv. Sửa đổi Tên liên hệ
![Screenshot (594)_LI](https://user-images.githubusercontent.com/92591165/142840870-1368d8fb-6619-4498-956c-7d5fcbcec77a.jpg)
v: Nhấn "Cập nhật" button
vi: Trở về trang chủ
![Screenshot (595)_LI](https://user-images.githubusercontent.com/92591165/142841374-3fa045ef-a101-46df-8fa1-7f745f7f78cc.jpg)
c. Kết quả thực tế: Không thay đổi tên liên hệ (Một lúc lâu mới thay đổi khi tải lại trang)
d. Kết quả mong đợi: Thay đổi tên liên hệ ngay tức khắc khi nhấn "Cập nhât" button

[https://drive.google.com/file/d/19WdYFvXvhhx52uewrkrmrAL3KrCHOCmj/view?usp=sharing](url)

**Comment by 31191026273** [comment]
Nhóm nên minh chứng bằng cách quay video load trên 3 phút theo yêu cầu trong hướng dẫn từ thầy nhé.

**Comment by 31191024561** [comment]
[https://drive.google.com/file/d/19WdYFvXvhhx52uewrkrmrAL3KrCHOCmj/view?usp=sharing](url)

**Comment by 31191024561** [comment]
> a. web browser: Cốc cốc b. Các bước phát hiện lỗi i. Truy cập vào trang http://muaban.net/ ii. Vào trang thông tin cá nhân (Đăng nhập bằng tài khoản Facebook) iii. Chọn danh mục Thông tin tài khoản iv. Sửa đổi Tên liên hệ ![Screenshot (594)_LI](https://user-images.githubusercontent.com/92591165/142840870-1368d8fb-6619-4498-956c-7d5fcbcec77a.jpg) v: Nhấn "Cập nhật" button vi: Trở về trang chủ ![Screenshot (595)_LI](https://user-images.githubusercontent.com/92591165/142841374-3fa045ef-a101-46df-8fa1-7f745f7f78cc.jpg) c. Kết quả thực tế: Không thay đổi tên liên hệ (Một lúc lâu mới thay đổi khi tải lại trang) d. Kết quả mong đợi: Thay đổi tên liên hệ ngay tức khắc khi nhấn "Cập nhât" button
> 
> [https://drive.google.com/file/d/19WdYFvXvhhx52uewrkrmrAL3KrCHOCmj/view?usp=sharing](url)
