### ISSUE TITLE
[Nhóm #3] Lỗi phi chức năng - Lượt download vẫn được tính khi download không thành công- https://scodeweb.com/

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/ST_K45_01#237]
A. Web browser: Microsoft Egde
B. Các bước phát hiện lỗi :
#1. Vui lòng xem lại issue #234 và thực hiện các bước.
#2. Click vào quản lý tài khoản "Chào,..." ở dòng trên cùng.
#3. Reload lại trang và tìm dòng "code download"
![image](https://user-images.githubusercontent.com/72399443/142883904-bb3d05e0-686f-4302-9888-65d0a5e4a517.png)
C. Kết quả thực tế: số lượng code download đã tăng lên.
D. Kết quả mong đợi: số lượng code download giữ nguyên.

**Comment by 31191020041** [comment]
Mình vừa làm thử và nó hiện ra màn hình cho download và download được mà không cần share nha bạn
![image](https://user-images.githubusercontent.com/92364035/142953620-41a06f8b-1134-4564-a09c-72c7e118f018.png)
![image](https://user-images.githubusercontent.com/92364035/142953654-6b5eeed6-a526-4da2-a830-bf6c25348bb6.png)
![image](https://user-images.githubusercontent.com/92364035/142953694-54cf2f39-30c5-427b-a099-f51c5f6b5901.png)

**Comment by ghost** [comment]
Minh xin phép mô tả lại kỹ hơn.
A. Web browser: Microsoft Egde
B. Các bước phát hiện lỗi :
#1. Đăng nhập vào website
#2. Click "free code", chọn một bài đăng bất kỳ, click "Miễn phí", sau đó click "download ngay"
#3. Click "Share source - download miễn phí"
![image](https://user-images.githubusercontent.com/72399443/142960206-22d5f4d2-9084-4164-8da8-dd9217d48950.png)
#4. Tắt cả hai pop up vừa hiện ra ( lưu ý: không click vào link download dự phòng)
![image](https://user-images.githubusercontent.com/72399443/142960259-b5ef02a3-890d-42a8-9f7a-b72558422c69.png)
![image](https://user-images.githubusercontent.com/72399443/142960323-7cca9c04-5ddf-4cd2-9ef2-84e21d562a17.png)
#5. Click vào quản lý tài khoản "Chào, ...." ở dòng trên cùng
#6. Reload lại trang và tìm dòng "code download"
C. Kết quả thực tế: Số lượng code download đã tăng lên mặc dù chưa thực hiện download
D. Kết quả mong đợi: số lượng codedownload vẫn giữ nguyên.

**Comment by ghost** [comment]
Mình đã mô tả lại chi tiết hơn, bạn xem lại giúp mình nhé

Vào Th 3, 23 thg 11, 2021 vào lúc 07:14 Nguyễn Thái Hiền <
***@***.***> đã viết:

**Comment by 31191020041** [comment]
mình nghĩ khi bạn bấm vào nút download, nó đã tính lượt download rồi. Vì không share được nên chưa hoàn thành bước download nên nó mới không tải xuống được. Bên dưới cũng đã có link dự phòng để bạn có thể tiếp tục download

**Comment by ghost** [comment]
Bạn cũng có nói là "Vì không share được nên chưa hoàn thành bước download nên nó mới **không tải xuống được**". Vậy là có lỗi rồi, mình chưa down được về máy mà nó đã tính thêm một lượt rồi.

**Comment by 31191020041** [comment]
Nhưng không share được nên chưa hoàn thành bước download là lỗi 234, vì ở lỗi 234 có lỗi nên mới k qua được bước download, vậy là bị trùng với lỗi 234 rồi

**Comment by 31191020041** [comment]
nhóm ơi, mình sẽ để là không phải lỗi. Khi nào nhóm có ý kiến nào khác để chứng minh đây là lỗi thì mình sẽ xem xét lại nhé
