### ISSUE TITLE
[Nhóm#2] Lỗi chức năng- Chức năng đăng ký chuyển điểm không hợp lệ- https://student.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191024352** [UEHMonQAQC/ST_K45_01#240]
Web Browser: Microsoft Edge
**Các bước để phát hiện lỗi:**
#1: Đăng nhập vào trang web bằng tài khoản người học : [https://student.ueh.edu.vn](url)
#2: Kéo xuống phần **" Chức năng trực tuyến"** chọn **"Nộp chứng chỉ"**
#3: Chọn **" Đăng ký chuyển điểm "** tại danh sách chứng chỉ ( Như hình)
![image](https://user-images.githubusercontent.com/92584158/142886632-321cdca8-e2d6-40e6-a1da-78db6ea987fc.png)
#4: Chọn **" Đăng ký "** ( Như hình)
![image](https://user-images.githubusercontent.com/92584158/142887055-45880510-1dd0-4516-9e08-140f3d49519d.png)

...
**Kết quả thực tế**
Mặc dù _"Không tìm thấy dữ liệu"_ nhưng **"Thao tác thành công"**
![image](https://user-images.githubusercontent.com/92584158/142886700-4264e770-8bdd-4b8b-8201-359698f3927f.png)

**Kết quả mong đợi**
Chỉ **Thao tác thành công** khi có dữ liệu cụ thể

**Comment by 31191020041** [comment]
mình có tham khảo thì thấy: đầu tiên, chứng chỉ quốc phòng k có chuyển điểm sang môn nào khác được, nên không có dữ liệu. Và khi bạn bấm đăng ký, nó không bắt buộc bạn phải nhập thông tin mới đăng ký được nên mới hiện thao tác thành công. Thao tác thành công ở đây là bạn đã đăng ký rồi, với dữ liệu là không có gì, dữ liệu này sẽ được xem xét.
