### ISSUE TITLE
[Nhóm#2] Lỗi phi chức năng- Lỗi XSS nhắn tin không hiển thị - https://lms.iuh.edu.vn

### ISSUE THREAD

**Issue by 31191026415** [UEHMonQAQC/ST_K45_01#241]
A. Web browser: Microsoft Egde
B. Các bước phát hiện lỗi : Như trong video: **https://bom.to/VideoXSS**
Kiểm tra lượng truy cập tại Semrush > 300 lượt truy cập: `https://www.semrush.com/`
![10](https://user-images.githubusercontent.com/92585805/145045160-43ee947e-f22f-4d96-90a3-eec1c3a93a96.png)

#1: Đăng nhập vào https://lms.iuh.edu.vn
#2 Click vào button messenger, sau đó nhập dòng mã `<script>alert"Nhóm2"</script>` và gửi cho một người bạn
![image](https://user-images.githubusercontent.com/92584158/145054358-a8677e38-ee70-44cf-a17f-9d0226f0cd87.png)

**Kết quả thực tế:**
Hiện thị tin nhắn nhưng không có nội dung
![image](https://user-images.githubusercontent.com/92584158/145054430-651a470b-29bb-4dae-9a45-9d906d39117d.png)
 Người nhận tin nhắn cũng không hiển thị nội dung, và có một dòng code lạ ( Ô cam của hình dưới ) 
![image](https://user-images.githubusercontent.com/92584158/145054716-3f788db7-c279-42da-8d6e-ac855a88a615.png)

**Kết quả mong đợi**
Hiển thị nội dung tin nhắn `<script>alert"Nhóm2"</script>`

**Comment by 31191020041** [comment]
Nhóm ơi, bổ sung cho mình các bước phát hiện lỗi nhé

**Comment by 31191026415** [comment]
Mình sửa lại r nha

**Comment by 31191020041** [comment]
Nhóm ơi, bổ sung cho mình bước kiểm tra lượng truy cập của trang ngoài nhé. Thầy yêu cầu trang ngoài phải có lượng truy cập trên 300/tháng

**Comment by 31191024352** [comment]
@31191020041  Nhóm tui cập nhật số lượng truy cập và thêm phần minh chứng rồi ă!!

**Comment by 31191020041** [comment]
Mình không thấy hiện đoạn script đó nên mình xin phép đóng lỗi này nhé
