### ISSUE TITLE
[Nhóm#2] Lỗi phi chức năng- Lỗi XSS về thông báo - https://student.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191024357** [UEHMonQAQC/ST_K45_01#242]
Web Browser: Microsoft Edge
Các bước để phát hiện lỗi:
#1: Đăng nhập vào trang web bằng tài khoản người học : [https://student.ueh.edu.vn](url)
#2: Vào **Nộp chứng chỉ** chọn Thêm mới/ Điều Chỉnh
#3: Nhập dòng lệnh <script>alert"Nhóm2"</script> vào ô Tổng điểm
#4: Nhấn Lưu thông tin
...
**Kết quả thực tế**
Thông báo xuất hiện không hiển thị nội dung chỉ có nút OK
![5 1](https://user-images.githubusercontent.com/92577042/142893661-af85ea9c-78cd-4254-b636-1f9350d88875.PNG)
![5 2](https://user-images.githubusercontent.com/92577042/142893681-403b5ac0-5f52-4adf-aef9-04d0e6cf479b.PNG)

**Kết quả mong đợi**
Thông báo xuất hiện nội dung đầy đủ

**Comment by 31191020041** [comment]
Nhóm ơi, mình xem lại thì đây chỉ là thông báo thôi, nếu trang chạy dòng code đó thì nó sẽ hiện dòng chữ "nhóm 2" nhé
