### ISSUE TITLE
[Nhóm#3] Lỗi phi chức năng - Có thể dò tìm password - https://bienniensukienhsv.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191025686** [UEHMonQAQC/ST_K45_01#249]
A. Web browser: Microsoft Egde
B. Các bước phát hiện lỗi:
i. #1 Truy cập vào trang https://bienniensukienhsv.ueh.edu.vn/Login
ii. #2: Gõ tên đăng nhập và mật khẩu sai nhiều lần
C.Kết quả thực tế : Tên đăng nhập và mật khẩu không đúng mà không bị khoá tài khoản.
D.Kết quả mong muốn : Khi nhập sai quá nhiều hệ thống sẽ hiển thị bạn có muốn lấy lại tài khoản hoặc thông báo về số lần nhập sai sẽ bị khoá tài khoản hoặc hệ thống được cài đặt Captcha hợp lý để hạn chế việc spam những request nhạy cảm khả dĩ có thể làm hỏng hệ thống (đăng ký tài khoản, đăng nhập…) để tăng tính bảo mật .

**Comment by 31191020041** [comment]
Bạn bổ sung video minh hoạ nha. Với lại trang này mình thấy không đăng nhập được

**Comment by 31191020041** [comment]
Mình xin phép không chấp nhận lỗi này với lí do không thể dò được mật khẩu. Khi nhóm có thể bổ sung thêm công cụ dò tìm mật khẩu, mình sẽ xem lại cho nhóm nhé
