### ISSUE TITLE
[Nhóm#8] Lỗi phi chức năng - Lỗi thời gian phản hồi upload quá lâu - https://shcd.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191024554** [UEHMonQAQC/ST_K45_01#251]
a. Web browser: Google Chrome - Version 95.0.4638.69 (Official Build) (64-bit).
Tốc độ mạng ổn định:
![image](https://user-images.githubusercontent.com/24526239/143032299-e8f5add9-0b4a-465e-a59c-ef59834177dc.png)

b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang [https://shcd.ueh.edu.vn/](https://shcd.ueh.edu.vn/)
ii. #2: Tiến hành đăng nhập (Sử dụng email sinh viên UEH để đăng nhập).
iii. #3: Click vào phần Họ tên và MSSV. Dropdown sẽ hiện ra.
![image](https://user-images.githubusercontent.com/24526239/141165942-e87cf3ff-e209-4575-be7b-a2abf8059cd7.png)
iv. #4: Click chọn "Hồ sơ". Chuyển hướng đến trang hồ sơ.
v. #5: Click chọn "Learning plans"
![image](https://user-images.githubusercontent.com/24526239/143030395-79870fe1-1b9a-4b0a-a1db-6c26f89e0300.png)
vi. #6: Ở trang Learning plans, click chọn "Evidence of prior learning"
![image](https://user-images.githubusercontent.com/24526239/143030520-10f8686e-6c93-4181-a11b-e93ab85a0a13.png)
vii. #7: Ở trang Evidence of prior learning, click chọn nút "Add new evidence".
![image](https://user-images.githubusercontent.com/24526239/143030587-2aa9e5d8-9afb-4e07-998c-f2bb7640e221.png)
viii. #8: Ở phần Files, click chọn icon thêm file.
![image](https://user-images.githubusercontent.com/24526239/143031004-d2b7d509-59a0-4c95-a690-045c2be2ecc7.png)
ix. #9: Click chọn "Choose File" và chọn tệp tin. (ở đây mình thử upload 2 video, 1 video 171MB, 1 video 1.11GB, cả 2 đều <2gb kích thước tệp tin cho phép tải lên).
![image](https://user-images.githubusercontent.com/24526239/143031309-6db2727f-90f0-41cb-9e44-b6af9d055d30.png)
x. #10: Click chọn button "Đăng tải tệp này"

c. Kết quả thực tế: Video 171MB upload thành công, Video 1.11GB upload đợi mãi đợi mãi..

- Link video 171MB: [Jump in](https://drive.google.com/file/d/1owDl0kQKHhHREz5VP2JwOOCH1ce3oMu9/view?usp=sharing)
- Link quá trình upload 171MB: [Jump in](https://drive.google.com/file/d/1z_CBbpJJ5deyYeOeEzurXXkaEvt2Cfx1/view?usp=sharing)

- Link video 1.11GB: [Jump in](https://drive.google.com/file/d/1umIv5FoJ6XLv1oE4nqbX1Z7fv-vkNF-k/view?usp=sharing)
- Link quá trình upload 1.11GB: [Jump in](https://drive.google.com/file/d/1PCcB5D2xoy58nX_93Hvn_JIwaYMoOV4a/view?usp=sharing)

d. Kết quả mong đợi: Upload thành công cả 2 video (vì đều thỏa < 2GB), Thời gian phản hồi của video 1.11GB tối đa là 5 phút (với tốc độ mạng ổn định).

**Comment by 31191024773** [comment]
Trùng với #181
