### ISSUE TITLE
[Nhóm#2] Lỗi phi chức năng- Lỗi XSS đăng ký ngoại trú sinh viên- https://student.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191024352** [UEHMonQAQC/ST_K45_01#252]
Web Browser: Microsoft Edge
**Các bước để phát hiện lỗi:**
#1: Đăng nhập vào trang web bằng tài khoản người học : [https://student.ueh.edu.vn](url)
#2: Điền thông tin cá nhân, bất kỳ ô input nào thì điền đoạn code " `<script>alert('Nhóm2')</script>.` "

_Ví dụ điền như hình_

![image](https://user-images.githubusercontent.com/92584158/143083310-7993d735-b6da-4a09-8131-4d7afec015f7.png)

...
**Kết quả thực tế**
Chỉ hiện thị pop up thông báo rỗng 

![image](https://user-images.githubusercontent.com/92584158/143083569-18c3b482-d965-42d3-9109-a28fe36d64bc.png)

**Kết quả mong đợi**
Chặn các đoạn script được chèn vào trước khi xử lý.

**Comment by 31191020041** [comment]
Nhóm ơi, mình xem lại thì đây chỉ là thông báo thôi, nếu trang chạy dòng code đó thì nó sẽ hiện dòng chữ "nhóm 2" nhé
