### ISSUE TITLE
[Nhóm#2] Lỗi phi chức năng- Lỗi XSS khi thay đổi mật khẩu- https://student.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191024352** [UEHMonQAQC/ST_K45_01#253]
Web Browser: Microsoft Edge
**Các bước để phát hiện lỗi:**
#1: Đăng nhập vào trang web bằng tài khoản người học : [https://student.ueh.edu.vn](url)
#2: Cạnh tên sinh viên chọn drop down ấn vào và chọn " **Đổi mật khẩu**" _( Như hình)_
![image](https://user-images.githubusercontent.com/92584158/143253654-b3be3434-b735-4f45-ad39-3416829771c4.png)
#3: Điền mật khẩu cũ và mật khẩu mới, riêng mật khẩu mới điền với dòng code JS sau: `<script>alert('Nhóm2')</script>.`
#4: Chọn "**Cập nhật mật khẩu**" và đăng xuất ra ngoài để đăng nhập lại. 
...
**Kết quả thực tế**
Hiển thị thông báo cảnh báo nguy hiểm
![image](https://user-images.githubusercontent.com/92584158/143254679-fade19ce-ee57-4681-a60c-47df2773672d.png)
Và khi đăng nhập lại trang bị lỗi xử lý yêu cầu
![image](https://user-images.githubusercontent.com/92584158/143254894-018e6626-082c-4cf8-8919-3f83a886a518.png)

**Kết quả mong đợi**
Chấp nhận mật khẩu là " `<script>alert('Nhóm2')</script>.` "

**Comment by 31191020041** [comment]
nhóm ơi, trang chỉ cảnh báo thôi chứ không thực hiện đoạn script đó nên mình từ chối lỗi này nhé
