### ISSUE TITLE
[Nhóm#3] -Lỗi phi chức năng - Ensure CORS response header values are valid - https://bienniensukienhsv.ueh.edu.vn

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/ST_K45_01#254]
A. Trình duyệt Microsoft Edge
B. Các bước phát hiện lỗi
#1. Truy cập vào trang https://bienniensukienhsv.ueh.edu.vn
#2. Mở Devtool (F12). Đây là một công cụ debugging được tích hợp sẵn vào trình duyệt, hỗ trợ lập trình viên **phát hiện lỗi** và can thiệp sâu vào hệ thống.
![image](https://user-images.githubusercontent.com/72399443/143383824-c126d27a-15ca-4059-bfe1-dd1ae17a0b0b.png)

#3. Click vào icon tin nhắn màu xanh góc trên bên phải (nên chia layout như hình trên để tiện việc xem xét)
#4. Ở thẻ Issues ,tìm đến Security và mở "Ensure CORS response header values are valid"
Tìm hiểu thêm lỗi CORS là gì: https://topdev.vn/blog/cors-la-gi/
![image](https://user-images.githubusercontent.com/72399443/143384193-f520f20e-0469-46a0-b8b0-6ad1f6884702.png)

#5. Tìm đến phần "AFFECTED RESOURCE"  và mở 3 request (các tài nguyên bị ảnh hưởng).
![image](https://user-images.githubusercontent.com/72399443/143384376-2d5dae9e-bc26-40e9-a09d-a4f1aca6e9a3.png)

C. Kết quả thực tế: Lỗi CORS đã được liệt kê trong danh sách lỗi cảnh báo của devtool.
D. Kết quả mong đợi: Lỗi CORS không được tồn tại trên hệ thống này.

**Comment by 31191020041** [comment]
Lỗi này thầy không chấp nhận nên mình xin phép đóng nhé
