### ISSUE TITLE
[Nhóm#3] -Lỗi phi chức năng - Content Security Policy of your site blocks some resources - https://bienniensukienhsv.ueh.edu.vn

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/ST_K45_01#255]
A. Trình duyệt Microsoft Edge
B. Các bước phát hiện lỗi:
#1. Truy cập vào trang https://bienniensukienhsv.ueh.edu.vn
#2. Mở Devtool (F12). Đây là một công cụ debugging được tích hợp sẵn vào trình duyệt, hỗ trợ lập trình viên phát hiện lỗi và can thiệp sâu vào hệ thống.
![image](https://user-images.githubusercontent.com/72399443/143385769-99fbd689-bce3-4d3d-87c2-84e79485b588.png)

#3. #3. Click vào icon tin nhắn màu xanh góc trên bên phải (nên chia layout như hình trên để tiện việc xem xét)
#4. Ở thẻ Issues, tìm đến Security và mở "Content Security Policy of your site blocks some resources"
![image](https://user-images.githubusercontent.com/72399443/143386133-d9ccdbff-1f79-4216-bc2a-d2e78ea5834d.png)

#5. Tìm đến phần "AFFECTED RESOURCE" và mở 1 directive (tài nguyên bị ảnh hưởng).
![image](https://user-images.githubusercontent.com/72399443/143386203-ab82dcce-044f-4cc7-aeac-c34b0f8c7626.png)

*Đây chính là nguyên nhân của lỗi phi chức năng được đề cập ở issues #209.
C. Kết quả thực tế: Content Security Policy đã được liệt kê danh sách lỗi cảnh báo trong devtool.
D. kết quả mong đợi: Không được liệt kê trong danh sách lỗi của devtool.

**Comment by 31191020041** [comment]
Lỗi này thầy không chấp nhận nên mình xin phép đóng nhé
