### ISSUE TITLE
[Nhóm#9] Lỗi chức năng - Không cần nhập đủ 2 ký tự vẫn có thể thực hiện công cụ search được - https://nhattao.com/

### ISSUE THREAD

**Issue by KhaiPhan127** [UEHMonQAQC/ST_K45_01#275]
A. Web browser: Google Chrome
B. Các bước phát hiện lỗi:
i. #1 Truy cập vào trang https://nhattao.com/
ii. #2 Thực hiện công cụ search với 1 ký tự ( yêu cầu của search là tối thiểu 2 ký tự )
C. Kết quả thực tế: Không báo lỗi, vẫn search được kết quả với 1 ký tự
![image](https://user-images.githubusercontent.com/85572844/143774666-f1d0974d-9425-47d3-ada3-1038f46ffb6f.png)
![image](https://user-images.githubusercontent.com/85572844/143774680-47db25ad-7f04-4484-9e8a-9695ebabadf3.png)
D. Kết quả mong đợi: Thông báo không search được, yêu cầu nhập thêm 1 ký tự

**Comment by 31141021447** [comment]
Cái này không phải lỗi nha
