### ISSUE TITLE
[Nhóm#2] Lỗi phi chức năng - Lỗi bảo mật thông tin - https://kytucxa.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191024357** [UEHMonQAQC/ST_K45_01#276]
Web Browser: Microsoft Edge
Các bước để phát hiện lỗi:
Kiểm tra lượng truy cập tại Semrush > 300 lượt truy cập: `https://www.semrush.com/`
![image](https://user-images.githubusercontent.com/92584158/145044426-9be2ab75-5fec-41df-a81e-4f6e99d6b0ed.png)

#1: Đăng nhập vào trang web [https://kytucxa.ueh.edu.vn/](url)
#2: Chọn **Thanh toán tiền nước** trong **Biểu mẫu**
#3: Chọn ktx Nguyễn Chí Thanh, phòng 101
#4: Kéo xuống phía dưới cùng chọn thanh toán, nhập mã số sinh viên của trường UEH bất kì
#5: Nhấn **Tìm kiếm**

**Kết quả thực tế**
Tên sinh viên ứng với MSSV đó hiện ra
![pcn 3 3](https://user-images.githubusercontent.com/92577042/143775980-8891523b-0602-499c-a60d-4d37eab45584.PNG)
![pcn 3 1](https://user-images.githubusercontent.com/92577042/143775984-4080c9fd-d27b-449b-a7c0-6deeda948b23.PNG)

**Kết quả mong đợi**
Phải nhập tên sinh viên để thông tin được bảo mật

**Comment by 31191020041** [comment]
Nhóm ơi, mình xem lại thì mã số sinh viên và tên sinh viên không tính là lộ thông tin
