### ISSUE TITLE
[Nhóm#2] Lỗi phi chức năng - Lỗi thông tin không được kiểm tra - https://kytucxa.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191024357** [UEHMonQAQC/ST_K45_01#277]
Web Browser: Microsoft Edge
Các bước để phát hiện lỗi:
#1: Đăng nhập vào trang web [https://kytucxa.ueh.edu.vn/](url)
#2: Chọn Thanh toán tiền nước trong Biểu mẫu (Chọn ktx Nguyễn Chí Thanh, phòng 101)
#3: Nhập MSSV không nội trú ở KTX
#4: Chọn thanh toán

**Kết quả thực tế**
Xác nhận thành công, hiển thị thông tin đã được gửi cho dù sinh viên đó không ở KTX
![pcn 3 1](https://user-images.githubusercontent.com/92577042/143776539-84d8bfb5-1277-4fc3-8844-b5c786efe6de.PNG)
![PCN 4](https://user-images.githubusercontent.com/92577042/143776543-dc45fe6e-4a46-44b7-89d8-90f0efbefe3e.PNG)

**Kết quả mong đợi**
Phải kiểm tra thông tin sinh viên đó trước khi được gửi đi

**Comment by 31191020041** [comment]
thông tin được gửi đi để người ta xem xét lại, ở đây trang này chỉ làm chức năng là gửi thông tin đi thôi, bạn chọn thanh toán sẽ có một trang thanh toán hiện ra và có các bước để bạn đóng tiền. Đây không phải lỗi nhé nhóm
