### ISSUE TITLE
[Nhóm#2] Lỗi phi chức năng - Lỗi XSS - https://myphammall.com

### ISSUE THREAD

**Issue by 31191024357** [UEHMonQAQC/ST_K45_01#279]
Web Browser: Microsoft Edge
Các bước để phát hiện lỗi:
#1: Truy cập vào trang web [https://myphammall.com](url)
#2: Nhập <script>alert(1)</script> vào **Tìm kiếm sản phẩm**

**Kết quả thực tế**
Xuất hiện lỗi XSS
![pcn 2](https://user-images.githubusercontent.com/92577042/143777347-a32b4a87-e79a-422d-9ada-effe62711719.PNG)

**Kết quả mong đợi**
Lỗi XSS được khắc phục

**Comment by 31191020041** [comment]
Nhóm ơi, bổ sung cho mình bước kiểm tra lượng truy cập của trang ngoài nhé. Thầy yêu cầu trang ngoài phải có lượng truy cập trên 300/tháng

**Comment by 31191020041** [comment]
Nhóm ơi, lỗi này buổi thứ 8 thầy bảo không chấp nhận nên mình đóng lỗi này nhé
