### ISSUE TITLE
[Nhóm#2] Lỗi phi chức năng - Lỗi không bảo mật thông tin sinh viên - http://www3.youth.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191024357** [UEHMonQAQC/ST_K45_01#284]
Web Browser: Microsoft Edge
Các bước để phát hiện lỗi:
#1: Truy cập vào trang web [http://www3.youth.ueh.edu.vn/](url)
#2: Chọn "Hoạt động đã cập nhật" nhấn "Xem"
#3: Chọn một hoạt động

**Kết quả thực tế**
Các thông tin về sinh viên (Tên, mã số, lớp,...)  xuất hiện công khai, bất cứ ai cũng có thể thấy. Các đối tượng bên ngoài dễ dàng đánh cắp thông tin
![7 pcn](https://user-images.githubusercontent.com/92577042/143781872-0e8fbfa7-e774-4971-b3f5-c3b378195012.PNG)

**Kết quả mong đợi**
Ít nhất cần phải đăng nhập vào trang web để xác minh sinh viên của trường

**Comment by 31191020041** [comment]
https://github.com/UEHMonQAQC/K41/issues/161 trùng lỗi này của k41 nhé
