### ISSUE TITLE
[Nhóm#9] Lỗi phi chức năng - Tải tài liệu miễn phí từ trang tính phí - https://123docz.net/ 

### ISSUE THREAD

**Issue by duchung0908** [UEHMonQAQC/ST_K45_01#312]
A. Web browser: Google Chrome và Extensions: Quick Javascript Switch
B. Các bước phát hiện lỗi:
i. #1 Truy cập vào trang https://123docz.net/ và đăng nhập( không bắt buộc )
ii. #2 Chọn 1 tài liệu bất kì, ta sẽ xem được 3 trang đầu
iii. #3 Bật Extensions: Quick Javascript Switch và trên URL thêm "text."  trước 123docz.net 
Kết quả lượt truy cập:
![image](https://user-images.githubusercontent.com/90156544/144886862-974b30b5-b893-493a-944e-ddf27cfa18ce.png)
C. Kết quả thực tế: Ta có thể xem hết tài liệu gồm 12 trang 
![image](https://user-images.githubusercontent.com/90156544/144885793-ba2993be-573c-40d8-b900-01cb8678205d.png)
D. Kết quả mong đợi: Tăng tính bảo mật và khuyến cáo là không nên xuất tài liệu bằng Javascript

**Comment by 31141021447** [comment]
Tài liệu full là 30 trang, mới chỉ xem được tới trang 12 thôi mà, vẫn phải trả phí mới xem đầy đủ được
