### ISSUE TITLE
[Nhóm#9] Lỗi giao diện - Bị thừa nút đăng bán - https://nhattao.com/

### ISSUE THREAD

**Issue by khiemhg1202** [UEHMonQAQC/ST_K45_01#33]
A. Web browser: Google Chrome
B. Các bước phát hiện lỗi:
i. #1 Truy cập vào trang https://nhattao.com/
ii. #2 Kéo xuống phần footer và chọn trang chủ
C. Kết quả thực tế: có 3 nút đăng bán

![UI_5](https://user-images.githubusercontent.com/91679167/140455378-d285cda8-06d7-467b-9b63-ae7a8b39cf26.png)

D. Kết quả mong đợi: chỉ nên có một nút đăng bán.

**Comment by khiemhg1202** [comment]
Cùng một trang mà tận 3 nút đăng bán để làm gì ạ

**Comment by 31141021447** [comment]
Đây là tính năng mà người làm web thiết kế để tiện cho người sử dụng có thể đăng bán khi sử dụng trên trang. Ví dụ khi kéo xuống cuối trang thì nút đăng bán ở đầu trang sẽ chỉ nằm ở đó, sẽ hơi bất tiện khi phải kéo ngược trở lại để đăng bán. Có thêm nút đăng bán nổi sẽ giúp quá trình đăng bán, thao tác được nhanh hơn.
