### ISSUE TITLE
[Nhóm#7] Lỗi chức năng-Lỗi điều hướng-http://muaban.net/

### ISSUE THREAD

**Issue by 31191024561** [UEHMonQAQC/ST_K45_01#40]
a. Web browser: Cốc Cốc
b. Các bước phát hiện lỗi
i. Truy cập vào https://muaban.net/
ii. Vào trang chủ
iii. Roll chuột xuống danh mục Ứng dụng & MXH
iv.Nhấp vào "Tải app trên App Store" button
![Screenshot (265)](https://user-images.githubusercontent.com/92591165/140629602-2019007f-6377-4fec-b34d-4dd2b8d773ac.png)

![Screenshot (278)](https://user-images.githubusercontent.com/92591165/140629645-33f13005-625b-4a09-9b25-0eae0e4632d8.png)
c. Kết quả thực tế: URL không được tìm thấy 
d. Kết quả mong đợi: Khôi phục URL

**Comment by 31191026273** [comment]
Tải ứng dụng trên App Store chỉ áp dụng trên điện thoại.
