### ISSUE TITLE
[Nhóm#7] Lỗi phi chức năng-Không có mô tả trong thuộc tính alt="" trong <img>-https://muaban.net/

### ISSUE THREAD

**Issue by 31191024561** [UEHMonQAQC/ST_K45_01#44]
a. Web Browser
b. Các bước phát hiện lỗi
i. Truy cập vào trang https://muaban.net/
ii. Ở trang chủ chọn giới thiệu ở Logo "Muaban.net"
![Screenshot (283)_LI](https://user-images.githubusercontent.com/92591165/140630813-72e60af4-726a-450d-864b-bd3ba157edf6.jpg)
iii. Ở trang giới thiệu, roll chuột xuống phần bài viết có thấy 2 img
![Screenshot (282)](https://user-images.githubusercontent.com/92591165/140631112-8c906239-a358-46de-ae89-98aebfcfc7ca.png)
![Screenshot (281)](https://user-images.githubusercontent.com/92591165/140631114-b4356592-2915-435e-b10d-dee4b4de0d6d.png)
iv. Nhấn chuột phải chọn "Xem nguồn trang"
v. Roll chuột xuống 1194, 1196
![Screenshot (284)_LI](https://user-images.githubusercontent.com/92591165/140631199-feca391f-af8d-4eb9-ab30-6f6679a96df1.jpg)
c. Kết quả thực tế: Không có mô tả trong tag alt=""
d. Kết quả mong đợi: Có phần mô tả trong img

**Comment by 31191026273** [comment]
Thẻ Alt thường để trống, và không ảnh hưởng đến việc truy cập trang, đây không phải là lỗi.
