### ISSUE TITLE
[Nhóm#7] Lỗi giao diện-Lỗi bố cục-https://muaban.net/

### ISSUE THREAD

**Issue by 31191024561** [UEHMonQAQC/ST_K45_01#45]
a.Web Browser: Cốc Cốc
b. Các bước phát hiện web
i. Truy cập vào https://muaban.net/
ii. Ở trang chủ roll chuột xuống mục Logo chọn Giới thiệu
![Screenshot (283)_LI](https://user-images.githubusercontent.com/92591165/140632576-3c7bd533-8e77-4c76-9591-54297672e4d1.jpg)
iii. Ở trang giới thiệu, roll xuống dưới phần footer
![Screenshot (287)](https://user-images.githubusercontent.com/92591165/140632615-b324ff0d-c638-4301-aa16-27e667448349.png)
c. Kết quả thực tế: Bố cục không đều
d. Kết quả mong đợi : Bố cục căn chính giữa block

**Comment by 31191026273** [comment]
Web đang áp dụng căn lề trái , là ý của người lập trình, không phải lỗi. Có thể đối chiếu sang mục THEO DÕI MUA&BÁN bên cạnh cũng đang áp dụng lối căn lề này, hầu như cái web khác đều sử dụng căn lề trái cho mục thông tin liên hệ.
