### ISSUE TITLE
[Nhóm#7] Lỗi phi chức năng-Không có mô tả trong thuộc tính alt="" trong <img>-https://muaban.net

### ISSUE THREAD

**Issue by 31191024561** [UEHMonQAQC/ST_K45_01#47]
a. Web browser: Cốc Cốc
b. Các bước phát hiện lỗi
i. Truy cập https://muaban.net/
ii. Ở trang chủ roll chuột xuống phía dưới chọn "giới thiệu " ở mục Logo
iii. Di chuyển con trỏ chuột đến mục Báo giá và nhấn chọn mục Bảng giá dành cho tin bất động sản có số nhà Hà Nội
![Screenshot (40)_LI](https://user-images.githubusercontent.com/92591165/140640376-8b38d7e6-4fef-4194-9b60-79bb8d5c108e.jpg)
iv. Ở mục Bảng giá dành cho tin bất động sản có số nhà Hà Nội có hiển thị 2 img
![Screenshot (34)](https://user-images.githubusercontent.com/92591165/140640434-2f86c7fc-41d2-46d6-89b6-ff82d28b0659.png)
![Screenshot (38)](https://user-images.githubusercontent.com/92591165/140640441-1dd77f2d-cd63-42b2-a7d7-955d351a944c.png)
v. Nhấn chuột phải rồi chọn "Xem nguồn trang"
vi. Roll chuột xuống dòng 1202, 1210
![Screenshot (43)_LI](https://user-images.githubusercontent.com/92591165/140640791-8bab9666-916b-400d-b6fb-4bb92e560c2e.jpg)
c. Kết quả thực tế: Không chứa phần mô tả trong thuộc tính alt trong tag <img>
d. Kết quả mong đợi : Có chứa phần mô tả trong thuộc tính alt

*Noted: Tương tự ở mục  Bảng giá dành cho tin bất động sản có số nhà TP HCM ( Nhấn chuột phải rồi chọn "Xem nguồn trang"----> Roll chuột xuống dòng 1216, 1225)
![Screenshot (42)_LI](https://user-images.githubusercontent.com/92591165/140640727-83c5d2b6-70b2-4fbe-ba05-08258b9c4b4b.jpg)

**Comment by 31191026273** [comment]
Thẻ Alt thường để trống, và không ảnh hưởng đến việc truy cập trang, đây không phải là lỗi.
