### ISSUE TITLE
[Nhóm#2] Lỗi chức năng - Không thu danh sách chức năng - https://student.ueh.edu.vn

### ISSUE THREAD

**Issue by 31191026415** [UEHMonQAQC/ST_K45_01#72]
Web Browser: Google Chrome
Các bước để phát hiện lỗi:
#1: Đăng nhập vào trang web bằng tài khoản người học : https://student.ueh.edu.vn
#2: Tại thanh sidebar, click vào **Trang cá nhân**, **Tra cứu thông tin**, **Chức năng trực tuyến** thì không thu các danh sách chức năng tương ứng lại.

**Kết quả thực tế**
Click vào **Trang cá nhân**, **Tra cứu thông tin**, **Chức năng trực tuyến** không thu danh sách chức năng tương ứng lại
![250873886_251969996952487_3194514614884963893_n](https://user-images.githubusercontent.com/92578055/140654272-c4d51c49-cf31-4662-897e-02ad88f2c6d1.png)

![251374346_323977812393689_6587248259803343648_n](https://user-images.githubusercontent.com/92578055/140653343-25cfb3e5-428a-4f24-a070-14fb16f8dd61.png)

![254302964_573405953954069_5123147555719909609_n](https://user-images.githubusercontent.com/92578055/140654348-c6241e49-bd2b-4a9f-b734-b3f4f9ad5a74.png)

**Kết quả mong đợi**
Click vào **Trang cá nhân**, **Tra cứu thông tin**, **Chức năng trực tuyến** thu danh sách chức năng tương ứng lại

**Comment by 31191020041** [comment]
Trang này không thu danh sách chức năng được, không phải lỗi nha nhóm
