### ISSUE TITLE
[Nhóm#6] Lỗi giao diện - Button đăng nhập bị ẩn  - https://chotot.vn/

### ISSUE THREAD

**Issue by 31191023216** [UEHMonQAQC/ST_K45_01#78]
A. Mở trình duyệt: Microsoft Edge
B. Các bước phát hiện lỗi
i. Truy cập vào trang Chợ tốt: [https://chotot.vn/](url)
ii. Bấm vào nút "Đăng tin"
iii. Hiển thị phần đăng nhập (Thông tin tài khoản đã được lưu từ lần đăng nhập trước)
C. Kết quả thực tế : Nút Đăng nhập tối và  không có hiệu ứng move hover như ảnh:

![image](https://user-images.githubusercontent.com/92626602/140704290-0184a347-ba44-4506-bd2c-b034d681bc70.png)

D. Kết quả mong đợi: Nút Đăng nhập sáng và có hiệu ứng move hover như ảnh:

![image](https://user-images.githubusercontent.com/92626602/140704248-347e4f14-20e8-4ebc-bce1-0bb6551da01c.png)

**Comment by 31191026273** [comment]
đây là do chưa chọn tài khoản đăng nhập. Hệ thống có thể lưu nhiều tài khoản khác nhau, khi ấn vào đăng tin hệ thống chỉ đang hiển thị tài khoản lưu gần nhất . Khi chọn tài khoản để đăng nhập thì nút đăng nhập mới sáng lên.
