### ISSUE TITLE
[Nhóm#6] Lỗi chức năng - Lưu thông tin khi khách hàng nhập sai dữ liệu Họ tên - https://www.chotot.com/

### ISSUE THREAD

**Issue by huyhaile13** [UEHMonQAQC/ST_K45_01#80]
A. Mở trình duyệt: Google Chrome
B. Các bước kiểm tra lỗi: 
 i. Truy cập vào trang Chợ Tốt  [https://www.chotot.com/](url) 
 ii. Đăng nhập vào tài khoản (tài khoản: 0379133271, mật khẩu: Hai11022001)
 iii.Bấm vào phần thông tin cá nhân 
![image](https://user-images.githubusercontent.com/92034330/140710215-615e095e-20ec-483f-967f-9d6b78b420a0.png)
 iv.Bấm vào Chỉnh sửa Hồ sơ xin việc
![image](https://user-images.githubusercontent.com/92034330/140710428-7556e242-c044-4c75-890a-27e3c1c8e2c0.png)
 v.Chỉnh sửa mục họ tên thành "-"
![image](https://user-images.githubusercontent.com/92034330/140710605-ee0d7c0f-760b-407a-997e-45daff4ddf0d.png)
 vi. Kéo xuống dưới và nhấp lưu thay đổi
![image](https://user-images.githubusercontent.com/92034330/140711655-898fa97b-78e4-46ce-ac49-1959af74ecda.png)

C. Kết quả thực tế: Trang web lưu thông tin với tên "-"
D. Kết quả mong đợi: Trang web thông báo Vui lòng nhập đúng Họ tên

**Comment by 31191026273** [comment]
ký tự "-" không phải là ký tự đặc biệt, ví dụ Lê-nin.
