### ISSUE TITLE
[Nhóm#6] Lỗi chức năng - Lỗi hiển thị thông báo - https://www.chotot.com/

### ISSUE THREAD

**Issue by 31191023216** [UEHMonQAQC/ST_K45_01#81]
A. Mở trình duyệt: Microsoft Edge
B. Các bước phát hiện lỗi
1. Truy cập trang: https://www.chotot.com/
2. Bấm vào tài khoản người dùng để chuyển hướng vào "Trang cá nhân"

![image](https://user-images.githubusercontent.com/92626602/140712381-4273d94e-52f6-477c-9210-6fd513a647e8.png)

3. Bấm vào "Chỉnh sửa trang cá nhân" 

![image](https://user-images.githubusercontent.com/92626602/140712440-1e3b3d4a-74e1-410e-8ff4-ec32b982ba9a.png)

4. Bấm vào nút sửa "Họ và tên"

![image](https://user-images.githubusercontent.com/92626602/140712475-a22b18a5-fea1-4e8f-8cb9-319972cec212.png)

5. Dữ liệu đưa vào:  "###!@!@!@#@$$"

![image](https://user-images.githubusercontent.com/92626602/140712516-27fd0e93-d56e-405d-8390-70259643cbc9.png)

6. Điền đúng email

C. Kết quả thực tế:

![image](https://user-images.githubusercontent.com/92626602/140710934-1ee491ed-a841-4c30-95a6-67a94c97f52b.png)

D.  Kết quả mong muốn: Thông báo hiển thị: "Không được chèn ký hiệu lạ trong ô tên"

**Comment by 31191026273** [comment]
Hệ thống không chấp nhận ký tự lạ và hiển thị thông báo không chấp được chèn ký tự lạ trong ô tên rồi mà. Chức năng này thực hiện đúng khi không cho save và hiển thị thông báo.
