### ISSUE TITLE
[Nhóm#7] - Lỗi chức năng - Trang hiển thị bị chuyển xuống cuối trang - https://lms.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191025356** [UEHMonQAQC/ST_K45_01#84]
a. Web Browser: Google Chrome Version 95.0.4638.69
b. Các bước để phát hiện lỗi:
#1: Đăng nhập vào trang web bằng tài khoản người học : https://lms.ueh.edu.vn/
#2: Ở dưới phần tổng quan các khóa học, click vào 12
#3: Xuất hiện dropdown, click vào Tất cả
c. Kết quả thực tế
Click vào Tất cả trang sẽ bị chuyển xuống cuối trang
![image](https://user-images.githubusercontent.com/92592402/140714978-03ae58e7-773a-488b-a9d9-b96429d87de9.png)
![image](https://user-images.githubusercontent.com/92592402/140716047-17d0d440-885b-46ff-b6a0-0d77deda7d4c.png)
d. Kết quả mong đợi
Trang sẽ được chuyển lên đầu trang

**Comment by 31191026273** [comment]
Đây là lỗi chức năng, không phải lỗi GUI, mình có chỉnh lại nha.
