### ISSUE TITLE
[Nhóm#7] - Lỗi giao diện - 2 dropdown bị đè lên nhau - https://lms.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191025356** [UEHMonQAQC/ST_K45_01#86]
a. Web Browser: Google Chrome Version 95.0.4638.69
b. Các bước để phát hiện lỗi:
#1: Đăng nhập vào trang web bằng tài khoản người học : https://lms.ueh.edu.vn/
#2: Bên phần dòng thời gian, click vào icon đồng hồ chọn "next 7 days"
![image](https://user-images.githubusercontent.com/92592402/140719372-e4ab82df-cd75-442f-91eb-068c0e372d85.png)
#3: Tiếp tục click vào icon sort chọn "sort by dates"
![image](https://user-images.githubusercontent.com/92592402/140719256-16da06c8-e02e-46fd-904a-66ad04145b7f.png)

c. Kết quả thực tế
Cả 2 dropdown bị đè lên nhau
![image](https://user-images.githubusercontent.com/92592402/140719506-d714df53-3857-41d1-bceb-901b6bbd8d36.png)
d. Kết quả mong đợi
2 dropdown không bị đè lên nhau, khi click ra ngoài hoặc click vào icon khác thì dropdown phải bị ẩn xuống

**Comment by 31191026273** [comment]
Lỗi bị trùng k44 : https://github.com/UEHMonQAQC/ST_K44/issues/188
